name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.0]
        apt-packages: [libcups2-dev]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Flake 8 and Requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.apt-packages }}
        sudo apt-get install libssl-dev swig
        python -m pip install --upgrade pip
        pip install flake8
        pip install coverage
        pip install coveralls 
        pip install setuptools
        pip install -r requirements.txt
    - name: Run flake8
      run: |
        flake8 edc_death_report
        python manage.py check
    - name: Run Tests
      run: |
          coverage run --source=edc_death_report manage.py test
          coverage xml -i
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.xml
        
